#+startup: showall

** When does vapor pressure deficit drive or reduce evapotranspiration?

This is the repository for reproducing the (currently pre-printed) manuscript:

Massmann, A., P. Gentine and C. Lin. /When does vapor pressure deficit
drive or reduce evapotranspiration?/ [[https://arxiv.org/abs/1805.05444][arXiv:1805.05444]]

The general directory structure is:

- src/ - all code
- dat/ - small data files used by code
- doc/ - any formal papers and presentations for the project
- etc/ - anything that doesn't fit into above, usually notes etc.

** Prerequisites
In order to reproduce the paper you will need:

- pipenv and Python 3
- wget
- tar and gzip
- GNUMake
- Texlive

** Reproducing research:

1. ~make install~ : installs dependencies and creates some needed
   directory structure.  Note that this step also downloads about 400
   MB of data from my collaborator Changjie, so it may take awhile.
2. ~make paper~ : does all analysis, makes all the figures/tables, and
   compiles the paper pdf (for submission to HESS) to ~doc/paper/vpd_et_paper_hess.pdf~.
3. ~make arxiv~ : does all analysis and compiles the arXiv paper
   to doc/paper/ms.pdf, including the actual ~.tar~ submission
   (~doc/paper/arxiv-submission.tar~).

If following these instructions does not work, please open an issue or
send me an email. Reproducibility is extremely important to me, so I am
happy to take the time to figure out any problems, especially because
I have not actually tried these steps on any other computer than mine
(so, for example, I might be missing some "prerequisites").

Also, if you come across any bugs please open an issue or send me an
email.

** Questions and comments

More generally, if you have any questions or comments on the paper
or otherwise, please open an issue (preferred) or send me an
email. Nothing would make me happier than this project starting some
public discussion about science!
