#+startup: showall

** When does vapor pressure deficit drive or reduce evapotranspiration?

This is the repository for reproducing the manuscript:

 Massmann, A., Gentine, P., & Lin, C. (2019). When does vapor pressure
 deficit drive or reduce evapotranspiration?. /Journal of Advances in
 Modeling Earth Systems/, 11. https://doi.org/10.1029/2019MS001790


The general directory structure is:

- src/ - all code
- dat/ - small data files used by code
- doc/ - any formal papers and presentations for the project
- etc/ - anything that doesn't fit into above, usually notes etc.

** Prerequisites
Reproducibility has been tested as of May 9, 2022 on Debian GNU/Linux
11 (bullseye). Software requirements are:

- Python 3
  - numpy
  - pandas
  - matplotlib
  - sympy
  - mpltoolkits.basemap
- tar and gzip
- GNU Make
- Texlive

You will also need some data from my collaborator
(~dat/changjie/vpd_data.tar.gz~). Email me (akm2203@columbia.edu) for
a link to that!

** Reproducing research:

1. ~make install~ : installs dependencies, creates some needed
   directory structure.
2. ~make~ : does all analysis and compiles the arXiv paper
   to doc/paper/ms.pdf, including the actual ~.tar~ submission
   (~doc/paper/arxiv-submission.tar~).

If following these instructions does not work, please open an issue or
send me an email. Reproducibility is important to me, so I am happy to
take the time to figure out any problems, especially because I have
not actually tried these steps on any other computer than mine. And,
as of the most recent reproducibility test (May 9, 2022), the build
system was a little shaky with not all file dependencies coded into
the Makefile.

Also, if you come across any bugs please open an issue or send me an
email.

** Questions and comments

More generally, if you have any questions or comments on the paper
or otherwise, please open an issue (preferred) or send me an
email. Nothing would make me happier than this project starting some
public discussion about science!
