#+startup: showall

** When does vapor pressure deficit drive or reduce evapotranspiration?

This is the repository for reproducing the manuscript:

 Massmann, A., Gentine, P., & Lin, C. (2019). When does vapor pressure
 deficit drive or reduce evapotranspiration?. /Journal of Advances in
 Modeling Earth Systems/, 11. https://doi.org/10.1029/2019MS001790


The general directory structure is:

- src/ - all code
- dat/ - small data files used by code
- doc/ - any formal papers and presentations for the project
- etc/ - anything that doesn't fit into above, usually notes etc.

** Prerequisites
In order to reproduce the paper you will need:

- pipenv and Python 3
- wget
- tar and gzip
- GNU Make
- Texlive

** Reproducing research:

1. ~make install~ : installs dependencies, creates some needed
   directory structure, and downloads data.  Note that this step
   downloads about 400 MB of data from my collaborator Changjie, so it
   may take awhile.
2. ~make arxiv~ : does all analysis and compiles the arXiv paper
   to doc/paper/ms.pdf, including the actual ~.tar~ submission
   (~doc/paper/arxiv-submission.tar~).

If following these instructions does not work, please open an issue or
send me an email. Reproducibility is extremely important to me, so I am
happy to take the time to figure out any problems, especially because
I have not actually tried these steps on any other computer than mine,
and to be honest I haven't fully tested the above steps on a clean
repository pull since before substantial changes during review. This is
on my to do list, but if you end up attempting this before I get to it
just reach out and I will fix any issues.

Also, if you come across any bugs please open an issue or send me an
email.

** Questions and comments

More generally, if you have any questions or comments on the paper
or otherwise, please open an issue (preferred) or send me an
email. Nothing would make me happier than this project starting some
public discussion about science!
